export default [
  {
    id:1,
    name:"HTML",
    img:"images/html.png",
    condition:"done"
  },
  {
    id:2,
    name:"CSS",
    img:"images/css.png",
    condition:"done"
  },
  {
    id:3,
    name:"JavaScript",
    img:"images/js.png",
    condition:"done"
  },
  {
    id:4,
    name:"PHP",
    img:"images/php.png",
    condition:"done"
  },
  {
    id:5,
    name:"React",
    img:"images/logo512.png",
    condition:"Loading"
  },
  {
    id:6,
    name:"Node.js",
    img:"images/nodeJs.png",
    condition:"None"
  },
  {
    id:7,
    name:"PhpMyAdmin",
    img:"images/phpmyadmin.png",
    condition:"done"
  },
  {
    id:8,
    name:"Corel",
    img:"images/corel.png",
    condition:"done"
  },
  {
    id:9,
    name:"PhotoShop",
    img:"images/PhotoShop.png",
    condition:"done"
  },
  {
    id:10,
    name:"Polyboard",
    img:"images/polyboard.png",
    condition:"done"
  }
]